# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NQrLgoGRJFeZZKSHOyiP2yNVXSnYOlkg
"""

required = input("Do you need a spherical mirror or spherical lens: ")

if required=="spherical mirror":
  finding = input("Enter wether you want to find the lenght of image,object,focus:")
  if finding=="focus":
    u= int(input("enter the object distance:"))
    v= int(input("enter the image distance:"))
    f=1/(1/v+1/u)
    print("focus disctance is",f)


  elif finding == "image":
    u= int(input("enter the object distance:"))
    f= int(input("enter the focus distance:"))
    v=1/(1/f-1/u)
    print("image distance is",v)


  elif finding == "object":
    v= int(input("enter the image distance:"))
    f= int(input("enter the focus distance:"))
    u=1/(1/f-1/v)
    print("objecy distance is",u)

  else:
    print("invalid input")


elif required == "spherical lens":
  finding1 = input("Enter wether you want to find the lenght of image,object,focus:")
  if finding1=="focus":
    u1= int(input("enter the object distance:"))
    v1= int(input("enter the image distance:"))
    f1=1/(1/v1-1/u1)
    print("focus disctance is",f1)


  elif finding1 == "image":
    u1= int(input("enter the object distance:"))
    f1= int(input("enter the focus distance:"))
    v1=1/(1/f1+1/u1)
    print("image distance is",v1)


  elif finding1 == "object":
    v1= int(input("enter the image distance:"))
    f1= int(input("enter the focus distance:"))
    u1=1/(-1/f1+1/v1)
    print("objecy distance is",u1)

  else:
    print("invalid input")

else:
  print("invalid input")

